### ISSUE TITLE
A question about your LC3

### ISSUE THREAD

**Issue by aviaryan** [stevenhan2/Sublime-LC3#1]
You write the file type in .tmlanguage as `ssraw`. Which compiler (or rather assembler) do you use for LC3. 
We in school use [this](http://people.cs.georgetown.edu/~squier/Teaching/HardwareFundamentals/LC3-trunk/docs/README-LC3tools.html) (LC301) on Windows and I think our syntax and the syntax clearly visible from your .tmlanguage are quite different.
Is it really so ?

Here is some correct code for our assembler.

```
;
 ; Program to multiply a number by the constant 6
 ;
 .ORIG x3050
LD R1, SIX
 LD R2, NUMBER
AND R3, R3, #0 ; Clear R3. It will
 ; contain the product.
 ; The inner loop
 ;
AGAIN ADD R3, R3, R2
ADD R1, R1, #-1 ; R1 keeps track of
 BRp AGAIN ; the iteration.
 ;
 HALT
 ;
 NUMBER .BLKW 1 #3
 SIX .FILL x0006
 .END
```

**Comment by FichteFoll** [comment]
I suspect the `ssraw` is a relict from http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html#final-touches

**Comment by stevenhan2** [comment]
I think they are the same after checking out the link you posted. Also `.asm` files aren't necessarily LC3. 

ssraw is there because I wrote this quickly and I have no clue what it does.

**Comment by aviaryan** [comment]
I realize the same after going through your .tmlanguage more thoroughly. But your package doesn't detect the "labels" (which IMHO are the most important part of LC3 code) and lists all commands/directives under `entity....` class which makes them flood up in Goto Symbol. 
Please fix that.
